version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.09.0-ce
    steps:
      - checkout
      - setup_remote_docker
          docker_layer_caching: true
          docker_version: 17.09.0-ce
      - run:
          name: Build application Docker image
          command: |
            docker build -t adobe/commerce-cif-ci-env .