version: 2
jobs:
  build_latest:
    working_directory: /app
    docker:
      - image: docker:17.09.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image (Latest)
          command: |
            docker build -t adobe/commerce-cif-ci-env:latest .
      - run:
          name: Push image to Docker Hub
          command: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push adobe/commerce-cif-ci-env:latest

  build_tag:
    working_directory: /app
    docker:
      - image: docker:17.09.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image (Tag)
          command: |
            docker build -t adobe/commerce-cif-ci-env:$CIRCLE_TAG .
      - run:
          name: Push image to Docker Hub
          command: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push adobe/commerce-cif-ci-env:$CIRCLE_TAG

workflows:
  version: 2
  build:
    jobs:
      - build_latest:
          filters:
            branches:
              only: master
      - build_tag:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/